style = "type"
language = "C"
usize_is_size_t = true
include_guard = "LITEPARSE_H"
cpp_compat = true
no_includes = true
sys_includes = ["stdbool.h", "stddef.h", "stdint.h"]

[parse]
parse_deps = false

[enum]
prefix_with_name = true
