/* Generated by the liteparse-c tests; rewrite with LITEPARSE_BLESS=1. */
#ifndef LITEPARSE_ABI_H
#define LITEPARSE_ABI_H

/* Expected LiteParseAbiDescriptor.layout_fingerprint for liteparse.h. */
#define LITEPARSE_ABI_FINGERPRINT 0xfe08f32098dc1cf6ULL

#endif
